# brew "amazon-ecs-cli"
# brew "autoconf"
# brew "automake"
brew "awscli"
# brew "bash"
# brew "bash-completion@2"
# brew "buildkit"
# brew "clisp"
# brew "cmake"
# brew "coreutils"
# brew "curl"
# brew "docker-completion"
# brew "docker-compose-completion"
# brew "ffmpeg"
# brew "findutils"
brew "fzf"
# brew "gcc"
# brew "gdb"
# brew "gh"
brew "git"
# brew "gnu-sed"
# brew "gnutls"
# brew "go"
# brew "gobject-introspection"
# brew "grep"
# brew "harfbuzz"
# brew "hub"
# brew "imagemagick"
# brew "jq"
# brew "krb5"
# brew "lf"
# brew "libass"
# brew "libevent"
# brew "libheif"
# brew "libmemcached"
# brew "libpq"
# brew "libyaml"
# brew "llvm"
brew "make"
# brew "man-db"
# brew "mono", link: false
# brew "mysql"
# brew "nkf"
# brew "nmap"
# brew "node"
# brew "oniguruma"
# brew "openjdk"
# brew "osx-cross/avr/avr-gcc@9"
# brew "packer"
# brew "pandoc"
# brew "php"
# brew "pkg-config"
# brew "pyenv"
# brew "pyenv-virtualenv"
# brew "pyenv-virtualenvwrapper"
# brew "python@3.8"
# brew "qmk/qmk/qmk"
# brew "qrencode"
# brew "reattach-to-user-namespace"
# brew "ripgrep"
# brew "ruby"
# brew "rust"
# brew "rustup-init"
# brew "srt"
# brew "telnet"
# brew "terraform"
# brew "terraform@0.12"
# brew "theora"
brew "tmux"
# brew "tree"
brew "vim"
# brew "wasm-pack"
# brew "wasm3"
# brew "wasmer"
# brew "watch"
# brew "wget"
# brew "yarn"
# brew "zlib"
brew "zsh"
brew "zsh-completions"
# cask "blackhole"
cask "docker"
# cask "dropbox"
# cask "evernote"
# cask "firefox"
cask "google-chrome"
# cask "google-cloud-sdk"
cask "google-japanese-ime"
# cask "inkscape"
# cask "intellij-idea"
cask "iterm2"
# cask "java"
# cask "jetbrains-toolbox"
# cask "obs"
cask "slack"
# cask "teensy"
# cask "vagrant"
# cask "virtualbox"
# cask "visual-studio-code"
# cask "wine-devel"
# cask "xquartz"
# tap "homebrew/brewdler"
# tap "homebrew/bundle"
# tap "homebrew/cask"
# tap "homebrew/cask-versions"
# tap "homebrew/core"
# tap "homebrew/services"
# tap "osx-cross/arm"
# tap "osx-cross/avr"
# tap "qmk/qmk"
# tap "tamakiii/tap", "git@github.com:tamakiii/homebrew-tap.git"

# tap "homebrew/cask-drivers"
# cask "kensington-trackball-works"
cask "discord"
cask "keeper-password-manager"
cask "visual-studio-code"
