tap "mutagen-io/mutagen"

brew "ca-certificates"
brew "awscli"
brew "fzf"
brew "git"
brew "jq"
brew "make"
brew "telnet"
brew "tmux"
brew "tree"
brew "vim"
brew "curl"
brew "wget"
brew "zsh"
brew "zsh-completions"
brew "zsh-autosuggestions"
brew "mysql-client"
brew "mutagen-io/mutagen/mutagen-compose"

brew "rust"
brew "php"
brew "node"
brew "go"

cask "docker"
cask "evernote"
cask "google-chrome"
cask "google-cloud-sdk"
cask "google-japanese-ime"
cask "iterm2"
cask "slack"
cask "discord"
cask "keeper-password-manager"
cask "visual-studio-code"
cask "session-manager-plugin"
cask "obsidian"
cask "dropbox"
