
install:
	apt install -y \
	  openssh-server \
	  nfs-common \
	  git \
	  vim \
	  zsh \
	  tmux \
	  openssh-server \
	  apt-transport-https \
	  ca-certificates \
	  curl \
	  software-properties-common

before:
	@echo "execute: sudo apt install make"
