# Arch Linux Package Manifest
# Similar to Cargo.toml for Rust projects, this file declares the system packages
# required for this dotfiles configuration.

[metadata]
name = "tamakiii-dotfiles"
description = "Personal Arch Linux dotfiles package dependencies"
version = "0.1.0"

# Core system packages - essential for basic functionality
[packages.core]
zsh = { reason = "Primary shell with advanced features" }
tmux = { reason = "Terminal multiplexer for session management" }
hx = { reason = "Helix editor - modern modal text editor", package = "helix" }
fzf = { reason = "Fuzzy finder for enhanced shell experience" }
uv = { reason = "Fast Python package installer and resolver", source = "aur" }
git = { reason = "Version control system" }

# Audio and media packages
[packages.audio]
alsa-utils = { reason = "ALSA utilities including aplay command" }
pipewire = { reason = "Modern audio server" }
wireplumber = { reason = "PipeWire session manager" }

# Bluetooth stack

[packages.bluetooth]
bluez = { reason = "Official Linux Bluetooth protocol stack" }
bluez-utils = { reason = "Bluetooth utilities and CLI tools" }
blueman = { reason = "GTK+ Bluetooth manager" }

# Development tools
[packages.development]
go = { reason = "Go programming language for workbench tools" }
nodejs = { reason = "Node.js runtime for npm-based MCP servers" }
npm = { reason = "Node.js package manager" }
base-devel = { reason = "Essential development tools meta-package" }

# Terminal and desktop environment
[packages.desktop]
ghostty = { reason = "Fast terminal emulator", source = "aur" }

# Network and connectivity
[packages.network]
avahi = { reason = "Service discovery daemon for AirPlay functionality" }
shairport-sync = { reason = "AirPlay audio receiver", source = "aur" }

# Optional dependencies - nice to have but not essential
[packages.optional]
overskride = { reason = "Modern Bluetooth device manager", source = "aur" }

# Development and optional tools that may not be needed on all systems
[packages.extra]
# docker = { reason = "Container platform", optional = true }
# terraform = { reason = "Infrastructure as code", optional = true, source = "aur" }

# Source definitions
[sources]
official = "Official Arch Linux repositories (pacman -S)"
aur = "Arch User Repository (yay -S or paru -S)"

# Package groups for different installation scenarios
[groups]
minimal = ["core"]
standard = ["core", "audio", "bluetooth", "development"]
full = ["core", "audio", "bluetooth", "development", "desktop", "network", "optional"]

# Notes and maintenance information
[notes]
last_updated = "2025-01-12"
arch_version = "rolling"
maintainer = "tamakiii"