theme = "base16_terminal"

[editor]
bufferline = "multiple"
true-color = true
soft-wrap.enable = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[keys.normal]
C-e = "scroll_down"
C-y = "scroll_up"
C-d = "half_page_down"
C-u = "half_page_up"

[keys.normal.space.p]
p = [
  "select_all",
  ":pipe $HOME/.local/bin/llm-text replace",
]
P = [
  "select_all",
  ":pipe $HOME/.local/bin/llm-text diff",
  ":set-language diff",
]
i = [
  "select_all",
  ":pipe $HOME/.local/bin/llm-text improve replace",
]
I = [
  "select_all",
  ":pipe $HOME/.local/bin/llm-text improve diff",
  ":set-language diff",
]

[keys.select.space.p]
p = ":pipe $HOME/.local/bin/llm-text replace"
P = [
  ":pipe $HOME/.local/bin/llm-text diff",
  ":set-language diff",
]
i = ":pipe $HOME/.local/bin/llm-text improve replace"
I = [
  ":pipe $HOME/.local/bin/llm-text improve diff",
  ":set-language diff",
]

[keys.normal.space.t]
e = [
  "select_all",
  ":pipe $HOME/.local/bin/llm-text translate-ja-en replace",
]
j = [
  "select_all",
  ":pipe $HOME/.local/bin/llm-text translate-en-ja replace",
]

[keys.select.space.t]
e = ":pipe $HOME/.local/bin/llm-text translate-ja-en replace"
j = ":pipe $HOME/.local/bin/llm-text translate-en-ja replace"

[keys.insert]
"C-[" = "normal_mode"
