theme = "fleet_transparent"

[editor]
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[keys.normal]
C-e = "scroll_down"
C-y = "scroll_up"
C-d = "half_page_down"
C-u = "half_page_up"

[keys.insert]
"C-[" = "normal_mode"
